packages:
  - infra/tsconfig-presets
  - infra/dep-presets
  - packages/monosync
  - packages/ui-web
  - packages/ui-ink

# minimumReleaseAge: 1440
blockExoticSubdeps: true
allowBuilds:
  msw: false
  nx: false
