name: Monosync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 */6 * *'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  create_mr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install --frozen-lockfile

      - name: monosync
        run: |
          pnpm run monosync:update
          pnpm install --no-frozen-lockfile

      - name: Push changes to a new branch
        id: push-changes
        run: |
          BRANCH_NAME="improvement-scheduled-monosync-update-$(date +'%Y%m%d')"
          git push origin HEAD:$BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
  
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ env.branch_name }}
          title: "Scheduled Monosync MR"
          body: "This is an automated pull request created by GitHub Actions."
          base: main # 目标分支